services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: quartz-app
    restart: always
    volumes:
      - ./content:/app/content:rw
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s     
      timeout: 10s       
      retries: 5         
      start_period: 60s  
  
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: quartz-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
    env_file:
      - .env
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/health" ,"||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s