name: Auth System Tests

on:
  push:
    branches: [main]
    paths:
      - 'quartz/auth/**'
      - 'tests/auth/**'
  pull_request:
    branches: [main]
    paths:
      - 'quartz/auth/**'

jobs:
  test-auth:
    runs-on: ubuntu-latest
    services:
      # Для интеграционных тестов
      test-db:
        image: alpine:latest
        options: >-
          --health-cmd "echo 'healthy'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run auth unit tests
        run: npm run test:auth:unit
        env:
          NODE_ENV: test

      - name: Run auth integration tests
        run: npm run test:auth:integration
        env:
          NODE_ENV: test
          AUTH_ENABLED: true
          JWT_SECRET: test-secret-key
          USER_DB_PATH: :memory:

      - name: Security audit
        run: npm audit --audit-level=moderate
