name: Docker build & push image

on:
  push:
    branches: [main]  # Изменено с v4
    tags: ["v*"]
  pull_request:
    branches: [main]  # Изменено с v4
    paths:
      - .github/workflows/docker-build-push.yaml
      - quartz/**
      - Dockerfile  # Добавляем наши Docker файлы
      - docker-compose.yml
  workflow_dispatch:

jobs:
  build:
    # Убираем ограничение - теперь работает для вашего форка
    runs-on: ubuntu-latest
    steps:
      - name: Set lowercase repository owner environment variable
        run: |
          echo "OWNER_LOWERCASE=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5.2.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/hrisancho/quartz-secure  # Ваш namespace
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64  # Multi-arch
